# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    # branches
    branches:
      only:
        - master
        - develop

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # install python and awscli
      - run:
          name: Install dependencies
          command: |
            sudo apt-get -y -qq install awscli

      - run:
          name: Make credentials
          command: |
            ./.make_credentials.sh

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # deploy to s3
      - deploy:
          name: Build and Deploy to S3
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn build:production && aws s3 sync ./build s3://app.reforestum.com/ --delete --region eu-west-1 --profile production && aws cloudfront create-invalidation --invalidation-batch file://invbatch.json --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths '/*' --profile production
            elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
              yarn build && aws s3 sync ./build s3://dev.reforestum.com/ --delete --region eu-west-1 --profile dev
            else
              echo "Not master branch so not deploying"
            fi
