export default {
  ROOT_URL: process.env.REACT_APP_ENV === 'production' ?
    'https://api.reforestum.com/v1/' :
    'https://reforestum-api.herokuapp.com/v1/',
  SIGNUP: 'auth/signup',
  LOGIN: 'auth/login/',
  REFRESH_TOKEN: 'auth/keep-alive',
  RECOVER: 'auth/password-recovery',
  RESET_PASSWORD: 'auth/reset-password',
  UPDATE_USER: 'user/update',
  UPDATE_PASSWORD: 'auth/update-password',
  KS_USER_DETAILS: 'auth/activation-profile',
  KS_SIGNUP: 'auth/activate-user',
  UPLOAD_AVATAR: 'user/upload-avatar',
  GET_PROFILE: 'user/detail',
  GET_INVOICES: 'user/invoices',
  GET_CERTIFICATES: 'user/certificates',
  GET_COUNTRIES: 'list/countries',
  GET_LANGUAGES: 'list/languages',
  GET_STEPS: 'co2/steps',
  CALC_CO2: 'co2/calculate',
  GET_SOURCES: 'co2/sources',
  ADD_SOURCE: 'co2/source',
  REMOVE_SOURCE: 'co2/source/',
  UPDATE_SOURCE: 'co2/source/',
  GET_BALANCE: 'co2/balance',
  GET_PUBLIC_PROFILE: 'user/public-profile',
  GET_PRICE: '/checkout/pre-order',
  PAYMENT: 'checkout/purchase',
  FORESTS: 'forests/',
  FOREST_SUMMARY: 'forests/summary',
  PUBLIC_FOREST_SUMMARY: 'forests/summary/',
  MY_FORESTS: 'forests/held',
  PUBLIC_FORESTS: 'forests/held/',
  PATRONS: '/patrons',
  GALLERY: '/gallery',
};
