import { delay } from './';

export const getCO2Sources = () => {
  return delay(300).then(() => {
    if (Math.random() < 0.05) {
      throw new Error('There was a problem fetching your sources');
    }

    return initialSources;
  });
};

export const addCO2Source = (value, name, periodicity) => {
  return delay(300).then(() => {
    if (!value || !name || !periodicity) {
      throw new Error('Please fill all the required steps');
    }

    return {
      id: Date.now(),
      value,
      name,
      periodicity,
      image: 'http://lorempixel.com/96/96/',
      relatives: []
    };
  });
};

export const removeCO2Source = (id) => {
  return delay(300).then(() => {
    if (!id) {
      throw new Error('ID required');
    }

    return {};
  });
};

export const updateCO2SourceFrequency = (id, periodicity) => {
  return delay(300).then(() => {
    // Do something to remove future jobs
    return {
      id,
      periodicity,
      // the API needs to return all the sources that were generated by
      // this source so we can cancel the recurrence in all of them
      relatives: [122, 123, 142]
    };
  });
};

const initialSources = [
  {
    id: 123,
    value: 12451,
    name: 'My Uber trip downtown',
    periodicity: 'daily',
    image: 'http://lorempixel.com/96/96/',
    relatives: [122, 142],
  },
  {
    id: 12346,
    value: 1235,
    name: 'Plane trip to the States',
    periodicity: 'none',
    image: 'http://lorempixel.com/96/96/',
    relatives: [],
  },
  {
    id: 51634,
    value: 12,
    name: 'Car 27 July 2017',
    periodicity: 'none',
    image: 'http://lorempixel.com/96/96/',
    relatives: [],
  },
  {
    id: 73245,
    value: 8157,
    name: 'Electric Bill',
    periodicity: 'monthly',
    image: 'http://lorempixel.com/96/96/',
    relatives: [],
  },
  {
    id: 122,
    value: 99999999999,
    name: 'My Uber trip downtown',
    periodicity: 'daily',
    image: 'http://lorempixel.com/96/96/',
    relatives: [123, 142],
  },
  {
    id: 142,
    value: 415,
    name: 'My Uber trip downtown',
    periodicity: 'daily',
    image: 'http://lorempixel.com/96/96/',
    relatives: [122, 123],
  },
];
